-- ============================================================
-- 19 · Seed demo wineries as REAL (wine-less) listings
-- At full go-live (MERGE_DEMO=false) demo WINES are dropped, but we keep every
-- winery as a real listing so it still appears (with a "coming soon" message
-- until it uploads live wines). Idempotent: inserts only wineries not already
-- present (case-insensitive by name). Run once before flipping MERGE_DEMO=false.
-- ============================================================
insert into public.wineries (name, region, country, tier, status)
select v.name, v.region, 'NZ', 'listed', 'onboarding'
from (values
  ('15 Minute Bottles', 'Canterbury'),
  ('Abel', 'Nelson'),
  ('Aitkens Folly', 'Central Otago'),
  ('Akitu', 'Central Otago'),
  ('Alexia', 'Wairarapa'),
  ('Alexia Urban Winery', 'Martinborough'),
  ('Allan Scott Family Winery', 'Marlborough'),
  ('Alpha Domus', 'Hawke''s Bay'),
  ('Amisfield Winery', 'Central Otago'),
  ('Amoise Wines', 'Hawke''s Bay'),
  ('Ant Moore Wines', 'Marlborough'),
  ('Ash Ridge Wines', 'Hawke''s Bay'),
  ('Askerne Estate', 'Hawke''s Bay'),
  ('Astrolabe Wines', 'Marlborough'),
  ('Ata Rangi', 'Martinborough'),
  ('Aurum Wines', 'Central Otago'),
  ('Awaroa Organic Winery', 'Waiheke Island'),
  ('Ayrburn', 'Central Otago'),
  ('Bald Hills Vineyard', 'Central Otago'),
  ('Batch Winery', 'Waiheke Island'),
  ('Big Sky', 'Martinborough'),
  ('Bilancia', 'Hawke''s Bay'),
  ('Bish Wines', 'Hawke''s Bay'),
  ('Black Barn Vineyards', 'Hawke''s Bay'),
  ('Black Estate', 'North Canterbury'),
  ('Blackenbrook Wines', 'Nelson'),
  ('Bladen Wines', 'Marlborough'),
  ('Blank Canvas Wines', 'Marlborough'),
  ('Blue Earth Estate', 'Wairarapa'),
  ('Bone Line', 'North Canterbury'),
  ('Bostock Wines', 'Hawke''s Bay'),
  ('Brennan Wines', 'Central Otago'),
  ('Brick Bay Wines', 'Auckland'),
  ('Brookfields Vineyards', 'Hawke''s Bay'),
  ('Burn Cottage', 'Central Otago'),
  ('Bushmere Estate Wines', 'Gisborne'),
  ('Cable Bay Wine', 'Auckland'),
  ('Caldera Vineyard Estate', 'Canterbury'),
  ('Cambridge Road Vineyard', 'Martinborough'),
  ('Carrick', 'Central Otago'),
  ('Chard Farm Winery', 'Central Otago'),
  ('Chateau Garage', 'Hawke''s Bay'),
  ('Chris Scott Wines', 'Hawke''s Bay'),
  ('Church Road', 'Hawke''s Bay'),
  ('Churton', 'Marlborough'),
  ('Clearview Estate', 'Hawke''s Bay'),
  ('Clos Henri Vineyard', 'Marlborough'),
  ('Clos Ostler', 'Waitaki Valley'),
  ('Cloudy Bay', 'Marlborough'),
  ('Coal Pit Wine', 'Central Otago'),
  ('Collaboration Wines', 'Hawke''s Bay'),
  ('Colombo Martinborough', 'Martinborough'),
  ('Coopers Creek', 'Auckland'),
  ('Craggy Range', 'Hawke''s Bay'),
  ('Craggy Range (Te Muna Road)', 'Martinborough'),
  ('Cuvar Winery', 'Hawke''s Bay'),
  ('Dashwood Wines', 'Marlborough'),
  ('De La Terre', 'Hawke''s Bay'),
  ('Decibel Wines', 'Hawke''s Bay'),
  ('Desert Heart', 'Central Otago'),
  ('Devotus', 'Martinborough'),
  ('Dicey', 'Central Otago'),
  ('Dog Point Vineyard', 'Marlborough'),
  ('Domaine Rewa', 'Central Otago'),
  ('Domaine Thomson Wines', 'Central Otago'),
  ('Dry River Wines', 'Martinborough'),
  ('Easthope', 'Hawke''s Bay'),
  ('Eaton Wines', 'Marlborough'),
  ('Elephant Hill', 'Hawke''s Bay'),
  ('Escarpment Vineyard', 'Martinborough'),
  ('Esses Wine Company', 'Marlborough'),
  ('Flaxmore Vineyards', 'Nelson'),
  ('Folding Hill Wine', 'Central Otago'),
  ('Forrest Wines', 'Marlborough'),
  ('Framingham Wines', 'Marlborough'),
  ('French Peak Vineyard', 'Canterbury'),
  ('Fromm Winery', 'Marlborough'),
  ('Georges Road Wines', 'Canterbury'),
  ('Gibbston Valley Wines', 'Central Otago'),
  ('Gibson Bridge Wines', 'Marlborough'),
  ('Goldie Estate', 'Waiheke Island'),
  ('Grasshopper Rock', 'Central Otago'),
  ('Grava Wines', 'Martinborough'),
  ('Grey Ridge', 'Central Otago'),
  ('Greystone Wines', 'North Canterbury'),
  ('Greywacke Vineyards', 'Marlborough'),
  ('Grove Mill', 'Marlborough'),
  ('Groves', 'Wairarapa'),
  ('Hamden Estate', 'Martinborough'),
  ('Hampshire Vineyards', 'Marlborough'),
  ('Hans Herzog Estate', 'Marlborough'),
  ('Harvest Restaurant', 'Marlborough'),
  ('Haythornthwaite Wines', 'Martinborough'),
  ('Herons Flight Winery And Vineyard', 'Auckland'),
  ('Home Fields', 'Wairarapa'),
  ('Hopesgrove', 'Hawke''s Bay'),
  ('Hunters Wines', 'Marlborough'),
  ('Immigrants Vineyard', 'Central Otago'),
  ('Jackson Estate', 'Marlborough'),
  ('Jasper Ridge Estate', 'Waiheke Island'),
  ('Johanneshof Cellars', 'Marlborough'),
  ('Johner Estate', 'Martinborough'),
  ('Johner Estate Winery', 'Wairarapa'),
  ('Judge Rock', 'Central Otago'),
  ('Jules Taylor Wines', 'Marlborough'),
  ('Kennedy Point Vineyard', 'Waiheke Island'),
  ('Kina Beach Vineyard', 'Nelson'),
  ('Kusuda Wines', 'Martinborough'),
  ('La Bella Rosa', 'Central Otago'),
  ('Lime Rock Wines', 'Hawke''s Bay'),
  ('Linden Estate Winery', 'Hawke''s Bay'),
  ('Lowburn Ferry', 'Central Otago'),
  ('Luna Estate', 'Martinborough'),
  ('Mahi Wines', 'Marlborough'),
  ('Man O War Vineyards', 'Auckland'),
  ('Maori Point Wines', 'Central Otago'),
  ('Margrain Vineyard Villas', 'Martinborough'),
  ('Marlborist', 'Marlborough'),
  ('Martinborough Vineyard', 'Martinborough'),
  ('Matawhero Wines Ltd', 'Gisborne'),
  ('Matt Connell Wines', 'Central Otago'),
  ('Maude Wines', 'Central Otago'),
  ('Mawhitipana Ridge Estate', 'Waiheke Island'),
  ('Maxim Wines', 'Hawke''s Bay'),
  ('Melton Estate', 'Canterbury'),
  ('Miro Vineyard', 'Auckland'),
  ('Mischief Wine', 'North Canterbury'),
  ('Mishas Vineyard', 'Central Otago'),
  ('Mission Estate Winery', 'Hawke''s Bay'),
  ('Moko Hills', 'Central Otago'),
  ('Mondillo Vineyards', 'Central Otago'),
  ('Monowai Estate', 'Hawke''s Bay'),
  ('Monte Christo Winery', 'Central Otago'),
  ('Mora', 'Central Otago'),
  ('Mount Edward Wines', 'Central Otago'),
  ('Moutere Hills', 'Nelson'),
  ('Moy Hall Vineyard', 'Martinborough'),
  ('Mt Difficulty Wines', 'Central Otago'),
  ('Mt Rosa', 'Central Otago'),
  ('Mu Wines', 'Auckland'),
  ('Mudbrick Vineyard', 'Waiheke Island'),
  ('Murdoch James Estate', 'Martinborough'),
  ('Nanny Goat Vineyard', 'Central Otago'),
  ('Nautilus Estate', 'Marlborough'),
  ('Neudorf Vineyards', 'Nelson'),
  ('Nga Waka Vineyard', 'Martinborough'),
  ('No 1 Family Estate', 'Marlborough'),
  ('Nockies Palette', 'Central Otago'),
  ('Novum', 'Marlborough'),
  ('Oak Estate Wines', 'Hawke''s Bay'),
  ('Obsidian', 'Waiheke Island'),
  ('Odyssey Wines', 'Gisborne'),
  ('Ohau Wines', 'Manawatū / Whanganui'),
  ('Omaha Bay Vineyard', 'Auckland'),
  ('Oraterra', 'Martinborough'),
  ('Palliser Estate', 'Martinborough'),
  ('Paritua Vineyards', 'Hawke''s Bay'),
  ('Pask', 'Hawke''s Bay'),
  ('Passage Rock Wines', 'Waiheke Island'),
  ('Peacock Sky Vineyard', 'Waiheke Island'),
  ('Pegasus Bay Winery', 'North Canterbury'),
  ('Pisa Range Estate', 'Central Otago'),
  ('Poderi Crisci', 'Waiheke Island'),
  ('Pond Paddock Vineyard', 'Martinborough'),
  ('Poppies Martinborough', 'Martinborough'),
  ('Postage Stamp Wines', 'Waiheke Island'),
  ('Pyramid Valley Vineyards', 'North Canterbury'),
  ('Q Wine', 'Waitaki Valley'),
  ('Quartz Reef', 'Central Otago'),
  ('Radburnd Cellars', 'Hawke''s Bay'),
  ('Rimu Grove Winery', 'Nelson'),
  ('Rippon Vineyard', 'Central Otago'),
  ('River T Winery', 'Waitaki Valley'),
  ('Riwaka River Estate', 'Nelson'),
  ('Rockburn', 'Central Otago'),
  ('Saint Clair Cellar Door', 'Marlborough'),
  ('Saorsa', 'Hawke''s Bay'),
  ('Sato', 'Central Otago'),
  ('Schubert Wines', 'Martinborough'),
  ('Seifried Estate', 'Nelson'),
  ('Seresin Estate 1', 'Marlborough'),
  ('Smith Sheth', 'Hawke''s Bay'),
  ('Soho Family Vineyards', 'Waiheke Island'),
  ('Soljans Estate Winery', 'Auckland'),
  ('Sorrell Wine', 'Marlborough'),
  ('South Edge Vineyard', 'Central Otago'),
  ('Spurlock Vineyards', 'Marlborough'),
  ('Spy Valley Wines', 'Marlborough'),
  ('Squawking Magpie Wines', 'Hawke''s Bay'),
  ('Steve Bird Wines', 'Marlborough'),
  ('Stewart Town Vineyard', 'Central Otago'),
  ('Stonyridge Vineyard', 'Waiheke Island'),
  ('Stormwood Wines', 'Waiheke Island'),
  ('Straight 8 Estate', 'Canterbury'),
  ('Swift Wines Ltd', 'Hawke''s Bay'),
  ('Tantalus Estate', 'Auckland'),
  ('Tarras Vineyards', 'Central Otago'),
  ('Te Awanga Estate', 'Hawke''s Bay'),
  ('Te Hera Estate', 'Martinborough'),
  ('Te Kairanga', 'Martinborough'),
  ('Te Kano', 'Central Otago'),
  ('Te Mania Richmond Plains Wines', 'Nelson'),
  ('Te Mata Estate', 'Hawke''s Bay'),
  ('Te Motu Vineyard', 'Waiheke Island'),
  ('Te Muna Valley Wines', 'Martinborough'),
  ('Te Pa Family Vineyards', 'Marlborough'),
  ('Te Rere Wines', 'Waiheke Island'),
  ('Te Whare Ra', 'Marlborough'),
  ('Terra Sancta', 'Central Otago'),
  ('Terrace Edge Vineyard', 'North Canterbury'),
  ('The Elder Pinot', 'Martinborough'),
  ('The Runholder', 'Martinborough'),
  ('The Three Chimneys', 'Martinborough'),
  ('Three Fates', 'Hawke''s Bay'),
  ('Three Miners Vineyard', 'Central Otago'),
  ('Thyme Hill Wines', 'Central Otago'),
  ('Tirohana Estate', 'Martinborough'),
  ('Tironui Estate', 'Hawke''s Bay'),
  ('Tiwaiwaka Winery', 'Martinborough'),
  ('Torlesse Wines', 'North Canterbury'),
  ('Trinity Hill', 'Hawke''s Bay'),
  ('Tupari Wines', 'Marlborough'),
  ('Unbound Wines', 'Central Otago'),
  ('Urlar', 'Wairarapa'),
  ('Vavasour Wines', 'Marlborough'),
  ('Vilaura', 'Hawke''s Bay'),
  ('Volcanic Hills Winery', 'Waikato / Bay of Plenty'),
  ('Vynfields', 'Martinborough'),
  ('Waipara Springs', 'Canterbury'),
  ('Wairau River Wines', 'Marlborough'),
  ('Wairiki Wines', 'Hawke''s Bay'),
  ('Waitiri Creek Wines', 'Central Otago'),
  ('Whitehaven Wine Company', 'Marlborough'),
  ('Wild Earth Wines', 'Central Otago'),
  ('Wild Waiheke', 'Waiheke Island'),
  ('Wither Hills', 'Marlborough'),
  ('Woodside Hill', 'Waiheke Island'),
  ('Wooing Tree Vineyard', 'Central Otago'),
  ('Wrekin Vineyard', 'Marlborough'),
  ('Yealands Wines', 'Marlborough')
) as v(name, region)
where not exists (
  select 1 from public.wineries w where lower(w.name) = lower(v.name)
);

-- Verify:  select count(*) from wineries;   -- should include all 240 demo wineries
